// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckziljwafruiabjdrike.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNremlsandhZnJ1aWFiamRyaWtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NzExMDMsImV4cCI6MjA3MDU0NzEwM30.qr9CMN2SXjkdF-dF0U2lszWaFaZRdZ80u0CFq-cX1F4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});